sudo: required
dist: trusty

language: node_js
node_js: '6.5.0'

cache:
  yarn: true
  directories:
    - node_modules
    - .ts-node-cache

before_install:
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2

install:
 - $HOME/.yarn/bin/yarn install

before_script:
 - export DISPLAY=:99.0

script:
 - travis_wait 30 npm run test